# Generated by Django 3.2.12 on 2022-06-13 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0151_productchannellisting_product_pro_discoun_3145f3_btree'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='origin_sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='origin_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clone_variants', to='product.productvariant'),
        ),
    ]
