# Generated by Django 3.2.12 on 2022-06-10 07:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0116_auto_20211207_0705'),
        ('product', '0151_productchannellisting_product_pro_discoun_3145f3_btree'),
    ]

    operations = [
        migrations.CreateModel(
            name='EProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_sku', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_product_sku', models.CharField(blank=True, max_length=255, null=True)),
                ('core_order_line', models.OneToOneField(on_delete=django.db.models.expressions.Case, related_name='eorderline', to='order.orderline')),
                ('original_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_product_variant', to='product.productvariant')),
            ],
        ),
    ]
