# Generated by Django 3.2.12 on 2022-06-13 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0152_auto_20220613_0240'),
        ('order', '0116_auto_20211207_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='origin_product_sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='origin_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_order_lines', to='product.productvariant'),
        ),
    ]
